# Generated by Django 3.2.11 on 2022-02-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20, null=True)),
                ('userid', models.CharField(max_length=128, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('desc', models.TextField(null=True)),
                ('finger_print', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('headers', models.TextField(null=True)),
                ('favicon_hash', models.TextField(null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=20, null=True)),
                ('port_list', models.TextField(null=True)),
                ('os_name', models.TextField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('related_domain', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTasks',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('target', models.TextField(null=True)),
                ('port_type', models.IntegerField(default=2)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('error', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('site', models.TextField(null=True)),
                ('host_name', models.TextField(null=True)),
                ('ip', models.CharField(max_length=20)),
                ('title', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('headers', models.TextField(null=True)),
                ('http_server', models.TextField(null=True)),
                ('body_length', models.IntegerField(null=True)),
                ('favicon', models.TextField(null=True)),
                ('fld', models.TextField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scantasks')),
            ],
        ),
        migrations.CreateModel(
            name='SiteFinger',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('icon', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('confidence', models.IntegerField(null=True)),
                ('version', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('finger', models.TextField(null=True)),
                ('siteinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PortInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('port_num', models.IntegerField(null=True)),
                ('service_name', models.TextField(null=True)),
                ('version', models.TextField(null=True)),
                ('product', models.TextField(null=True)),
                ('protocol', models.TextField(null=True)),
                ('ip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ipinfo')),
            ],
        ),
        migrations.AddField(
            model_name='ipinfo',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scantasks'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('domain', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('record', models.TextField(null=True)),
                ('ips', models.TextField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scantasks')),
            ],
        ),
    ]
