# Generated by Django 3.2.11 on 2022-02-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portinfo',
            name='ip_addr',
            field=models.TextField(null=True),
        ),
    ]
